name: tag-release workflow

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/wireguard-container-endpoint

jobs:
  #
  # upload tag release to dockerhub
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Date
        run: |
          echo "RELEASE_DATE=$(date +'%y%m%d')" >> ${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{version}}.${{ env.RELEASE_DATE }}
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            BUILD_VERSION=${{ steps.tag_name.outputs.SOURCE_TAG }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
